### ISSUE TITLE
Images on the front page are bigger than they need to be

### ISSUE THREAD

**Issue by FraserThompson** [thephilosophersmeme/thephilosophersmeme.com#3]
The TPM header image, lovely as it is, does not need to be 250kb. There are also some small thumbnail images associated with posts which are in the hundreds of kilobytes.

Currently the frontpage is 1mb and with some optimization I think we could half this.

**Comment by FraserThompson** [comment]
Resized a bunch of images and brought the size of the frontpage down to 500kb from 1mb.

**Comment by jcahill** [comment]
do you want to automate optimization? pngquant or similar

**Comment by FraserThompson** [comment]
At this point the posts are so infrequent and made by so few people that I think automating it might be overkill and possibly not even possible with the siteleaf setup we've got. Instead I might write some documentation and best practices on how to compress images and make sure everyone who's posting follows it.
