### ISSUE TITLE
fix bolds in the comments of autist article

### ISSUE THREAD

**Issue by leucotic** [thephilosophersmeme/thephilosophersmeme.com#5]
http://thephilosophersmeme.com/2017/03/27/defining-normie-casual-ironist-and-autist-in-internet-subcultures/ check 🅱️omments

**Comment by FraserThompson** [comment]
Fixe🅱️. @seongyher thought he need to put a space between the ** and the : for some reason.

**Comment by leucotic** [comment]
thanks 🅱️ae
