### ISSUE TITLE
did someone fu🅱️ w/ the masthead? looks 🅱️lurry to me

### ISSUE THREAD

**Issue by leucotic** [thephilosophersmeme/thephilosophersmeme.com#6]

**Comment by FraserThompson** [comment]
Yes I did because it was like 700kb for no good reason and now it's 90kb instead. It looks sharp to me in Windows on a 4k display. Are you on a retina display by any chance? I haven't tested it on a retina display because I don't have access to one, I might need to double the resolution of the image.

**Comment by leucotic** [comment]
yea im on retina, it looks blurry af, pls double, you still have the original 700kb one, right?

**Comment by FraserThompson** [comment]
Yeah, source control means nothing ever gets deleted. 

I've doubled the size of the image and turned it into a JPG,. It's roughly doubled the size but still our overall page size is pretty small so I'm not too bothered.

You can close this if it fixes the problem.

**Comment by leucotic** [comment]
ya it's fixed, thanks

**Comment by jcahill** [comment]
@leucotic
upstream tweaks you can do directly from Ps to avoid fraser's all-seeing eye:

* Save for Web > PNG-8 > […]
  - this case: can get it down to 174K w/o fiddling
  - (smaller and higher fidelity than current)

* a plugin like [SuperPNG](www.fnordware.com/superpng/)
  - RGB mode: typically vast improvements over Save For Web
  - other modes: results vary

also, png size balloons when you reencode jpg artefacts:

![2017 04 19_tpm-header_cleanup-tiled](https://cloud.githubusercontent.com/assets/4574990/25178528/1c97eb38-24d4-11e7-9735-81107c81c2c8.png)

background cleanup would cut size down

@FraserThompson
my primary display's a [spyder](http://spyder.datacolor.com/display-calibration/)-calibrated digitizer. feel free to assign me to any full-neurosis-mode compression tasks if you want
